### ISSUE TITLE
Test Review

### ISSUE THREAD

**Issue by danielhe4rt** [AlyssonSantos1/BackendTest#1]
## Code Review

Tem muita coisa a ser melhorada e eu creio que dificilmente cê vai conseguir alguma coisa sem estudar as bases da Framework e do PHP. Deixei alguns links e comentários pra te ajudar nessa padronização. 

Boa sorte na sua jornada!

### Roteamento

Nesse espaço já vi que há uma certa inexperiência sobre convenções de REST API's. 

```php
// api.php


// Por quê existe uma regra de negócio tão importante dentro // do roteador? Isso já te desclassifica imediatamente 
// dependendo da qualidade da empresa que você quer entrar.
Route::post('/login', function(Request $request) {

    if(Auth::attempt(['email' => $request->email, 'password' => $request->password])){
        $user = Auth::user();
        $token = $user->createToken('JWT');
        return response()->json($token->plainTextToken, 200);
    }

    return response()->json('Failed to Login', 400);
});

// Você poderia usar um padrão de rotas, tais como: 
// -> Antes
Route::get('/', [BookCollection::class, 'getAll']);
Route::post('/added', [BookCollection::class, 'create']);
Route::put('/updated/{id}', [BookCollection::class, 'update']);
Route::delete('/delete/{id}', [BookCollection::class, 'destroy']);

// -> Depois
Route::get('/', [BooksController::class, 'getBooks']);
Route::post('/books', [BooksController::class, 'postBook']);
Route::put('/books/{id}', [BooksController::class, 'putBook']);
Route::delete('/books/{id}', [BooksController::class, 'deleteBook']);

```

> [!TIP]
> Note que eu troquei o nome do seu Controller de `BookCollection` para `BooksController`. Collection no Laravel tem outra proposta, que é guardar um "super array" com várias funcionalidades e já o Controller é o próximo passo quando você fala de roteamento.

### Models

```php

namespace App\Models;

use app\Models\BookStory; // PSR-4 mal aplicada por falta de cuidado, o correto seria "App\"
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BookStory extends Model
{
    use HasFactory;

    protected $table = 'book_stories';

    protected $fillable = ['name','ISBN', 'value'];

    public $timestamps = false; 

}
```

* O nome da Model está errado:
	* ❌ - BookStory
	* ✅ - BookStore
* Desabilitar os `$timestamps` sendo que é parte do Laravel e do Eloquent só por não estar no enunciado, também mostra inexperiência na framework e pouco entendimento da importância dos campos `created_at` e `updated_at`

### Controllers

* Falta de tipagem de retorno
* Mal uso do mass create do Eloquent (metodo create)
* Usar Model::all() ao invés do Model::paginate() sem entender o risco que isso pode fazer em grandes bancos de dados já é algo pra desclassificar.
* `update()` voltando um json com status 200 sendo que deveria ser 4xx como error
* `update()` poderia ser validado a existencia do conteúdo direto nas rotas. 
* Utilização de mass assignment do Laravel ao invés de setar item por item.
* `delete()` sem necessidade de fazer vários if's após encontrar o dado final

### Links Úteis

- Roteamento do Laravel: https://laravel.com/docs/10.x/routing
- Laravel Timestamps: https://laravel.com/docs/10.x/eloquent#timestamps
- Eloquent Insert: https://laravel.com/docs/10.x/eloquent#inserting-and-updating-models
- PSR-4: https://www.treinaweb.com.br/blog/psr-4-a-recomendacao-de-autoload-do-php
- RESTful API's: https://www.hostinger.com.br/tutoriais/api-restful

**Comment by AlyssonSantos1** [comment]
Valeu cara @DanielHe4rt Obrigado por tudo vai me servir d base pra estudar
